# Copyright (c) 2020 Huawei Technologies Co., Ltd.
# Licensed under CC BY-NC-SA 4.0 (Attribution-NonCommercial-ShareAlike 4.0 International) (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode
#
# The code is released for academic research use only. For commercial use, please contact Huawei Technologies Co., Ltd.
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file contains content licensed by https://github.com/xinntao/BasicSR/blob/master/LICENSE/LICENSE

#### general settings
name: train
use_tb_logger: true
model: DehazeFlow
distortion: sr
scale: 4
gpu_ids: [ 0 ]

#### datasets
datasets:
  train:
    name: RESIDE_128_tr
    mode: PATH
    dataroot_all: D:/DataSet/RESIDE_HDF5/train/
    quant: 32

    use_shuffle: true
    n_workers: 1  # per GPU
    batch_size: 1
    GT_size: 152

    crop: true
    from_paths_list: true
    path_root:
      - D:\PycharmProjects\SRFlow-master\datasets\ots_clear_train.txt
      - D:\PycharmProjects\SRFlow-master\datasets\ots_hazy_train.txt
    path_num: 313950

  val:
    name: RESIDE_128_va
    mode: PATH
    dataroot_all: D:/DataSet/RESIDE_HDF5/val/
    quant: 32

    crop: false
    from_paths_list: true
    path_root:
      - D:\PycharmProjects\SRFlow-master\datasets\ots_clear_val.txt
      - D:\PycharmProjects\SRFlow-master\datasets\ots_hazy_val.txt
    path_num: 500

#### Test Settings
dataroot_GT: D:\DataSet\SOTS\indoor\gt
dataroot_HZ: D:\DataSet\SOTS\indoor\hazy
model_path: D:\PycharmProjects\SRFlow-master\trained_models\its_best.pth
heat: 0.1 # This is the standard deviation of the latent vectors

#### network structures
network_G:
  which_model_G: DehazeFlowNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
  upscale: 4
  train_RRDB: false
  train_RRDB_delay: 0.5

  flow:
    K: 16
    L: 3
    noInitialInj: true
    coupling: CondAffineSeparatedAndCond
    additionalFlowNoAffine: 2
    split:
      enable: true
    fea_up0: true
    stackRRDB:
      blocks: [ 1, 8, 15, 22 ]
      concat: true

#### path
path:
#  pretrain_model_G: D:\PycharmProjects\SRFlow-master\pretrained_models\772000_G.pth
#  G_complete: true
  strict_load: true
  resume_state: auto

#### training settings: learning rate scheme, loss
train:
  manual_seed: 10
  lr_G: !!float 2e-4
  weight_decay_G: 0
  beta1: 0.9
  beta2: 0.999
  lr_scheme: MultiStepLR
  warmup_iter: -1  # no warm up
  lr_steps_rel: [ 0.5, 0.75, 0.9, 0.95 ]
  lr_gamma: 0.5
  weight_fl: 1
  weight_l1: 0
  weight_l2: 0


  niter: 10000000
  val_freq: 2000
  tb_freq: 50

#### validation settings
val:
  heats: [ 0.0 ]
  n_sample: 1
  print_freq: 50

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e3
